---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  test-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Run build
          command: yarn run build
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Lint code files
          command: yarn run lint
workflows:
  version: 2
  build:
    jobs:
      - test-build
      - lint
